### ISSUE TITLE
Error with no data output in Pihi Plugin in Cacti 1.2.2

### ISSUE THREAD

**Issue by subarusyd** [xmacan/plugin_pihi#2]
Hi

The pihi plugin is installed and active but i am getting this error as follows in cacti log file. No output is being displayed on the pihi tab.

Can you please help? Also cannot Enable Ping history on the form as it comes with error **"If you enable pihi you have to select availability to ping/ping or snmp/ping and snmp"**

Thanks
michael

2019/03/19 10:08:01 - CMDPHP SQL Backtrace: (/plugins/pihi/pihi.php[148]:db_fetch_assoc(), /lib/database.php[450]:db_fetch_assoc_prepared(), /lib/database.php[464]:db_execute_prepared())
--
2019/03/19 10:08:01 - CMDPHP ERROR: A DB Row Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'and date between date_sub('2019-03-19 09:15:39',interval 8 minute) and '2019-03-' at line 1
2019/03/19 10:08:01 - CMDPHP SQL Backtrace: (/plugins/pihi/pihi.php[124]:db_fetch_cell(), /lib/database.php[360]:db_fetch_cell_prepared(), /lib/database.php[376]:db_execute_prepared())
2019/03/19 10:08:01 - CMDPHP ERROR: A DB Cell Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'and date > '2019-03-19 09:15:39'' at line 1
2019/03/19 10:08:01 - CMDPHP SQL Backtrace: (/plugins/pihi/pihi.php[120]:db_fetch_cell(), /lib/database.php[360]:db_fetch_cell_prepared(), /lib/database.php[376]:db_execute_prepared())
2019/03/19 10:08:01 - CMDPHP ERROR: A DB Cell Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'and date < '2019-03-19 09:15:39'' at line 1
2019/03/19 10:08:01 - CMDPHP SQL Backtrace: (/plugins/pihi/pihi.php[117]:db_fetch_cell(), /lib/database.php[360]:db_fetch_cell_prepared(), /lib/database.php[376]:db_execute_prepared())
2019/03/19 10:08:01 - CMDPHP ERROR: A DB Cell Failed!, Error: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'and date between date_sub('2019-03-19 09:15:39',interval 8 minute) and '2019-03-' at line 1

**Comment by xmacan** [comment]
Which version of PiHi?
Please show output of SQL query: select * from plugin_pihi_setting;

**Comment by xmacan** [comment]
For this "If you enable pihi you have to select availability to ping/ping or snmp/ping and snmp" please edit host and choose in Downed Device Detection Ping or Ping and snmp uptime

**Comment by subarusyd** [comment]
Thanks so much for your reply

I will check it out. The php version is 7.2 on ubuntu 18.0 lts server.

**Comment by subarusyd** [comment]
Thanks

Will check it out and hopefully that works

**Comment by xmacan** [comment]
Please try github version now. I fix few things

**Comment by subarusyd** [comment]
Thanks.

I have downloaded and installed the new pihi version.

I am not seeing the pihi DB syntax errors anymore in cacti log. 

The funny thing is when i change the device settings "downed detection" to  Ping or SNMP uptime and enable Ping history it accepts the save fine but when i go back to the device again later on from Devices menu the Ping History ends up as Disabled state.  have tried multiple options of the Downed detection option  including ICMP subcategory but same result.

Plugin Ping history remains in Disabled state even after multiple times i try to enable it.

No errors in cacti log except the pihi notifications below.  The Pihi tab shows the Devices i tried to enable Ping History from the drop down list ; But the display comes up underneath as "No Data".  No output for any devices for any time period in the drop down list. The Devices Plugin Ping history stays disabled.

Any ideas?

**Log Shows intervals as below:**

 CMDPHP PIHI STATS: hosts: 1. Duration: 0.000

**Comment by xmacan** [comment]
You are right. I have version 1.2.2 too and the same bug. But in my case Pihi works. I will fix it ASAP.
Try this: go to Pihi, choose host and on the right side are two arrows (in the middle could be date and time). Try to click to arrow.

**Comment by xmacan** [comment]
Please install actual version from github. Deinstall and install new version and try. I have fixed few things - Edit device now correctly displays PIng history settings.

**Comment by xmacan** [comment]
second problem solved. I found that problem was with using pihi and topx together. There was variable with the same name and it made problem

**Comment by subarusyd** [comment]
Thanks So Much. you are the best. It working all good now.. Thanks millions agaign.

**Comment by subarusyd** [comment]
Both very good cacti plugins. highly commendable
